from enum import Enum

class ResponseStatus(Enum):
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_VALID = "FILE_VALID"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_PROCESSING_SUCCESS = "FILE_PROCESSING_SUCCESS"
    FILE_PROCESSING_FAILED = "FILE_PROCESSING_FAILED"
    FILE_PROCESSING_RESET = "FILE_PROCESSING_RESET"
    NO_FILES_TO_PROCESS = "NO_FILES_TO_PROCESS"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    INSERT_INTO_VECTORDB_FAILED = "INSERT_INTO_VECTORDB_FAILED"
    INSERT_INTO_VECTORDB_SUCCESS = "INSERT_INTO_VECTORDB_SUCCESS"
    VECTORDB_COLLECTION_RETURNED= "VECTORDB_COLLECTION_RETURNED"
    VECTORDB_SEARCH_ERROR = "VECTORDB_SEARCH_ERROR"
    VECTORDB_SEARCH_SUCCESS = "VECTORDB_SEARCH_SUCCESS"

    